[package]
name = "rust_gdext"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.2.3" }
itertools = "0.14.0"
ndarray = { version = "0.16.1", features = ["rayon"] }
rayon = "1.10.0"
